
<!-- End icon above -->
<!-- Generated by HtaHub -->
<!-- NOTE: Any modifications must be edited in a binary-safe editor! -->
<!-- Start HTA -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
    <head>
        <hta:application
            icon="#"
            id='{{frame}}'
            applicationName='{{name}}'
            border='thick'
            borderStyle='raised'
            caption='yes'
            innerBorder='yes'
            minimizeButton='yes'
            maximizeButton='yes'
            navigable='yes'
            scroll='no'
            scrollFlat='no'
            singleInstance='no'
            showInTaskbar='yes'
            sysMenu='yes'
            windowstate='maximize'>
                <title>{{name}}</title>
        </hta>
    </head>
    <frameset>
        <frame scrolling='yes' application='yes' trusted='yes' src='{{url}}'></frame>
    </frameset>
</html>
